POST http://localhost:9000/api/insert/task HTTP/1.1
content-type: application/json

{
	"plan_id": 1,
	"name": "ауауауауы шавухаа",
	"content": "где",
	"date_start": "2020-07-17",
	"date_end": "2020-07-18",
	"result": 0
}
