'use strict'
const resources = {
	genericDbError: "Ошибка подключения к базе данных",
	dbError: msg => { return {error_message: msg, error_flag: true} },
	serverRunning: port => { return `Сервер запущен по адресу: http://localhost:${port}`},
	morganString: ':method :url :status :res[content-length] - :response-time ms',
	frontendOrigin: 'http://localhost:3000',
	entriesOnPage: 5,
	defaultExpressPort: 9000,

	inserted: {inserted: true},
	updated: {updated: true},
	deleted: {deleted: true},
	empty: {empty: true},

	loginSql: 'select name, id as user_id, role_id from users where email = ? and password = ?',
	getPlansWorkerSql: 'select plans.id as plan_id, users.name as name, worker_id, positions.name as position, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, super_id, hr_id, steps.name as step, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result, comment, grades.name as grade from users left join plans on plans.worker_id = users.id left join grades on grades.id = plans.grade_id left join positions on positions.id = plans.position_id left join steps on steps.id = plans.step_id where users.id = ?',
	getUserNameSql: 'select name from users where id = ?',
	getTasksSql: 'select id, name, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, content, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result from tasks where plan_id = ?',
	getPlansSuperSql: 'select plans.id, users.name as name, positions.id as position_id, positions.name as position, grades.name as grade,  worker_id, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, super_id, hr_id, step_id, steps.name as step, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result, grade_id, comment  from plans left join users on users.id=plans.worker_id left join grades on grades.id = plans.grade_id left join positions on positions.id = plans.position_id left join steps on steps.id = plans.step_id where super_id = ? limit ?, ?',
	getPlansHrSql: 'select plans.id, users.name as name, positions.id as position_id, positions.name as position, grades.name as grade,  worker_id, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, super_id, hr_id, step_id, steps.name as step, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result, grade_id, comment  from plans left join users on users.id=plans.worker_id left join grades on grades.id = plans.grade_id left join positions on positions.id = plans.position_id left join steps on steps.id = plans.step_id limit ?, ?',
	getDictGradesSql: 'select id, name from grades',
	getDictNamesSql: 'select id, name from users where role_id = ?',
	getDictStepsSql: 'select id, name from steps',
	getDictPositionsSql: 'select id, name from positions',
	insertPlanSql: 'insert into plans (worker_id,position_id,date_creation,super_id,hr_id,step_id,date_start,date_end,result,grade_id,comment) values (?,?,curdate(),?,?,1,?,?,?,?,?)',
	insertTaskSql: 'insert into tasks (plan_id,name,date_creation,content,date_start,date_end,result) values (?,?,curdate(),?,?,?,?)',
	updatePlanSql: 'update plans set worker_id = ?, position_id = ?, super_id = ?, hr_id = ?, step_id = ?, date_start = ?, date_end = ?, result = ?, grade_id = ?, comment = ? where id = ?',
	updateTaskSql: 'update tasks set plan_id = ?, name = ?, content = ?, date_start = ?, date_end = ?, result = ? where id = ?',
	updateTaskResultSql: 'update tasks set result = ? where id = ?',
	deletePlanSql: 'delete from plans where id = ?',
	deleteTaskSql: 'delete from tasks where id = ?',

	apiPath: '/api',
	loginPath: '/login',
	getPlansWorkerPath: '/get_worker_data',
	getTasksPath: '/get_tasks',
	getPlansSuperPath: '/get_plans_super',
	getPlansHrPath: '/get_plans_hr',
	getDictGradesPath: '/dict/grades',
	getDictNamesPath: '/dict/names',
	getDictStepsPath: '/dict/steps',
	getDictPositionsPath: '/dict/positions',
	insertPlanPath: '/insert/plan',
	insertTaskPath: '/insert/task',
	updatePlanPath: '/update/plan',
	updateTaskPath: '/update/task',
	updateTaskResultPath: '/update/task_result',
	deletePlanPath: '/delete/plan',
	deleteTaskPath: '/delete/task'
}

module.exports = resources
