'use strict'
const resources = {
	generic_db_error: "Ошибка подключения к базе данных",
	db_error: msg => { return {error_message: msg, error_flag: true} },
	server_running: port => { return `Сервер запущен по адресу: http://localhost:${port}`},
	frontend_origin: 'http://localhost:3000',
	inserted: {inserted: true},
	updated: {updated: true},
	deleted: {deleted: true},
	empty: {empty: true},
	entriesOnPage: 5,
	default_express_port: 9000,
	login_sql: 'select name, id as user_id, role_id from users where email = ? and password = ?',
	get_plans_worker_sql: 'select plans.id as plan_id, users.name as name, worker_id, positions.name as position, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, super_id, hr_id, steps.name as step, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result, comment, grades.name as grade from users left join plans on plans.worker_id = users.id left join grades on grades.id = plans.grade_id left join positions on positions.id = plans.position_id left join steps on steps.id = plans.step_id where users.id = ?',
	get_user_name_sql: 'select name from users where id = ?',
	get_tasks_sql: 'select id, name, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, content, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result from tasks where plan_id = ?',
	get_plans_super_sql: 'select plans.id, users.name as name, positions.id as position_id, positions.name as position, grades.name as grade,  worker_id, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, super_id, hr_id, step_id, steps.name as step, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result, grade_id, comment  from plans left join users on users.id=plans.worker_id left join grades on grades.id = plans.grade_id left join positions on positions.id = plans.position_id left join steps on steps.id = plans.step_id where super_id = ? limit ?, ?',
	get_plans_hr_sql: 'select plans.id, users.name as name, positions.id as position_id, positions.name as position, grades.name as grade,  worker_id, DATE_FORMAT(date_creation, "%d.%m.%Y") as date_creation, super_id, hr_id, step_id, steps.name as step, DATE_FORMAT(date_start, "%d.%m.%Y") as date_start, DATE_FORMAT(date_end, "%d.%m.%Y") as date_end, result, grade_id, comment  from plans left join users on users.id=plans.worker_id left join grades on grades.id = plans.grade_id left join positions on positions.id = plans.position_id left join steps on steps.id = plans.step_id limit ?, ?',
	get_dict_grades_sql: 'select id, name from grades',
	get_dict_names_sql: 'select id, name from users where role_id = ?',
	get_dict_steps_sql: 'select id, name from steps',
	get_dict_positions_sql: 'select id, name from positions',
	insert_plan_sql: 'insert into plans (worker_id,position_id,date_creation,super_id,hr_id,step_id,date_start,date_end,result,grade_id,comment) values (?,?,curdate(),?,?,1,?,?,?,?,?)',
	insert_task_sql: 'insert into tasks (plan_id,name,date_creation,content,date_start,date_end,result) values (?,?,curdate(),?,?,?,?)',
	update_plan_sql: 'update plans set worker_id = ?, position_id = ?, super_id = ?, hr_id = ?, step_id = ?, date_start = ?, date_end = ?, result = ?, grade_id = ?, comment = ? where id = ?',
	update_task_sql: 'update tasks set plan_id = ?, name = ?, content = ?, date_start = ?, date_end = ?, result = ? where id = ?',
	delete_plan_sql: 'delete from plans where id = ?',
	delete_task_sql: 'delete from tasks where id = ?',
	morgan_string: ':method :url :status :res[content-length] - :response-time ms',
	api_path: '/api',
	login_path: '/login',
	get_plans_worker_path: '/get_worker_data',
	get_tasks_path: '/get_tasks',
	get_plans_super_path: '/get_plans_super',
	get_plans_hr_path: '/get_plans_hr',
	get_dict_grades_path: '/dict/grades',
	get_dict_names_path: '/dict/names',
	get_dict_steps_path: '/dict/steps',
	get_dict_positions_path: '/dict/positions',
	insert_plan_path: '/insert/plan',
	insert_task_path: '/insert/task',
	update_plan_path: '/update/plan',
	update_task_path: '/update/task',
	delete_plan_sql: '/delete/plan',
	delete_task_path: '/delete/task'
}

module.exports = resources
